version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "gb-backend"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1rpi9ryqg77ny"
s3_prefix = "gb-backend"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

